# Default values for nodejs , fastapi, mariadb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  frontend:
    repository: chkion1234/prj-frontend
    tag: "arm-v6"  # 기본 태그 설정

  mariadb:
    repository: mariadb
    tag: "10.6.19-focal"

  admin:
    repository: chkion1234/prj-admin
    tag: "arm-v6"

  visitor:
    repository: chkion1234/prj-visitor
    tag: "arm-v6"

service:
  frontend:
    port: 3000

  mariadb:
    port: 3306

  admin:
    port: 8000

  visitor:
    port: 8050
